# global: { scrape_interval: 15s }
# scrape_configs:
#   - job_name: 'node'
#     static_configs: [ { targets: ['monitoring-node-exporter-server:9100'] } ]
#   - job_name: 'web'
#     static_configs:
#       - targets: ['web-frontend-server:80']

# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'node'
#     static_configs:
#       - targets: ['monitoring-node-exporter-server:9100']

#   - job_name: 'web'
#     metrics_path: '/'  # tạm thời để target UP
#     static_configs:
#       - targets:
#           - 'web-frontend-server:80'
#           - 'web-frontend-server1:80'
#           - 'web-frontend-server2:80'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['monitoring-node-exporter-server:9100']

  - job_name: 'web'
    static_configs:
      - targets: ['web-frontend-server:80']
    metrics_path: '/metrics'
